### ISSUE TITLE
华为P9看不到

### ISSUE THREAD

**Issue by Luhangh** [JasonQS/Anti-recall#1]

**Comment by Luhangh** [comment]
开启了调试模式，通知栏显示撤回不完整， qq微信内部点击撤回消息提示重复，或者是上一条消息

**Comment by JasonQS** [comment]
华为我是测试过可以的, 你可能需要重启, 另外请仔细看帮助

**Comment by Luhangh** [comment]
可能是手机问题把  15秒息屏辅助功能就自动关掉了。

**Comment by JasonQS** [comment]
大佬好好看帮助好吗.....我记得我写了如果自动关掉要给权限的啊

**Comment by Luhangh** [comment]
好的  大佬。  多谢
