### ISSUE TITLE
小米六是不是不适用？

### ISSUE THREAD

**Issue by wuhongjun15** [JasonQS/Anti-recall#10]
我的手机是小米六，系统版本是MIUI9，刚刚下载安装了防撤回软件，服务功能打开之后，再打开微信或QQ并没有提示，之后的撤回微信没反应，QQ提示我打开软件之前的撤回消息看不到，事实上我是已经打开了，请问是现在的QQ微信的版本变高，不适配还是小米手机的不适配？

**Comment by JasonQS** [comment]
写着目前版本不可用啦

**Comment by wuhongjun15** [comment]
好吧好吧，期待下次能用。
emmm，我发现老哥你这个思路很棒啊，如果有双眼睛一直盯着屏幕，是不会漏掉信息的，那我们就把他发的消息，后天监视保存下来，根据微信和QQ的可以撤回消息的时间，只保存可以撤回的，不能撤回的后台自动清理，这样就不会很占空间~

**Comment by JasonQS** [comment]
嘻嘻谢谢，不过其实，文本数据都挺小的

**Comment by JasonQS** [comment]
新版发布了

**Comment by wuhongjun15** [comment]
太好了，我赶紧试试！辛苦大佬~

**Comment by wuhongjun15** [comment]
出现问题了，Gradle sync failed: Connection refused: connect！怎么办?

**Comment by JasonQS** [comment]
删除原来的gradle.properties就好了，或者重新clone
