### ISSUE TITLE
旧版不能用了么

### ISSUE THREAD

**Issue by parks1234** [JasonQS/Anti-recall#11]
03-18 09:01:08.610 16976-16976/? E/MessageCaptor:                         v6: 3 package name: com.tencent.mm 	location: Rect(924, 1776 - 1068, 1920) 	text: null 	description: 更多功能按钮，已折叠 	class name: android.widget.ImageButton 	focusable: true 	
03-18 09:01:08.610 16976-16976/? E/MessageCaptor: Get Name ERROR !
03-18 09:01:08.911 16976-16976/? W/MessageCaptor: Single Click
03-18 09:01:08.948 16976-16976/? I/MessageCaptor: Searching...
03-18 09:01:08.949 16976-16976/? E/MessageCaptor: name is null !
03-18 09:01:08.962 16976-16976/? W/X-Toast: 显示的是: 无法获取联系人名字,
                                            请打开调试功能再试一次,
                                            并联系软件作者

**Comment by JasonQS** [comment]
对呢 新版快出来了

**Comment by JasonQS** [comment]
新版出来了
