### ISSUE TITLE
OPPO 手机装的 5.0.4 闪退

### ISSUE THREAD

**Issue by bitbert** [JasonQS/Anti-recall#17]
帅哥，
OPPO 手机装的 5.0.4 闪退。
ColorOS V3.0
Android V6.0.1

**Comment by N214** [comment]
+1 
一加三
FreedomOS
Andrioid 8

**Comment by wonder566** [comment]
荣耀9 emui8.0 android8.0 闪退

**Comment by JasonQS** [comment]
release 5.1.1 已解决闪退问题
