### ISSUE TITLE
MIUI10 (Android 8.0.0) 开启一段时间后闪退

### ISSUE THREAD

**Issue by idealclover** [JasonQS/Anti-recall#20]
手机：小米MIX2
系统：MIUI10 (Android 8.0.0)
故障描述：启动并给予权限后正常，一段时间后提示“Anti-recall已经停止”；再次启动无法正常查看被撤回消息；再次尝试授予权限时发现权限已被授予，撤销权限重新授予后正常使用。

**Comment by JasonQS** [comment]
谢谢反馈, 不知是否有出错日志呢
