### ISSUE TITLE
最新版的几个问题和建议

### ISSUE THREAD

**Issue by imbadark** [JasonQS/Anti-recall#21]
**APP整体的UI和功能实现觉得很nice, 先表示感谢** ~~的确是目前非root下见过最好的了:1st_place_medal: 
不过还是有以下一些问题反馈, 仅供参考: 
1. PC版微信自动登录在几个用了Miui的机型上测试都是失效的. 不知道原因? (不知是否有**语言匹配**问题?比如系统设置是**英文**的时候), 
2. 就以tim举例, 聊天界面的消息撤回虽然是可以点击文字+图片, 但是多条撤回的时候图片就看不到了,比如依次发送 ":a :图片1 :b  "三条消息,撤回 第一二或者 二三条 , 发现点击后全是文字. 且顺序容易错乱... 可能是读取存储. 然后图片不能查看, 这样消息稍多一点, 就会很快被覆盖, 不知为何不一起存储下来给个地方便随时查看,而只是临时放在聊天窗口?
3. wechat也有一些问题,比如消息截取的时候截取了所有弹出框的消息, 包括"XX message has recalled" 这种, 觉得可以对元素做一下简单的筛选, 不然一段时间没看消息可能会非常多, 查找撤回的消息很麻烦, 而且那个下拉的UI默认是收起来的, 建议可以默认展开一下, 有时候比较难拉, 右滑删除有时候会闪退..  话说TIM关闭收到所有消息记录(本来是想只看撤回消息) , 测试发现所有消息都会消失, 而且再测试也不出来. 而且发现wechat这边的消息弹出是不能和tim一样被控制不允许修改的(就是tim撤回消息是不会被修改的, 但是wechat还是会秒被改成XX has recalled a msg)?  还是说暂时没有做...
4. 软件开启了白名单/锁定(Miui10/9) ,进程倒是不会如 #20 被杀,  但是按返回发现每次还是退出程序了, 第二此点进都会重新加载启动界面, 不知道是什么原因? 包括设置了开机自启但是点开发现还是重新加载启动界面, 但是有时候消息貌似有记载. 再就是默认在Miui上文件读取权限是?. 并非允许,但是软件并不会自动去请求, 而是直接导致读取撤回图片失败, 这个可以也加一下**读取权限**检测(或**提醒**)
5. 关于wechat只能截取系统消息列表, 不能在聊天时截取信息的问题, 我想到的简单思路就是**同时**在PC开一个wechat 或web-wechat, 然后那边聊天, 并且不关闭手机提醒...  如果用手机的时候, 就用那边开启个python插件. 当然总归比较蛋疼..  

以上是目前想起来比较明显的问题和可能的建议, 再次感谢开源和维护~

PS: _日志的话没有Xposed很难输出...或者有什么简单办法输出运行日志?_ 再就是小Bug的确有点多(不包括闪退这种...有没有一个**更方便**的方式反馈一下, 比如XX group/mail或**软件内**快速获得日志提交问题)

**Comment by JasonQS** [comment]
十分感谢如此用心的 issue

1 可能哪里出了问题, 虽然我有适配中文和英文的通知栏检测. 由于实在少用微信(尤其是电脑上) 所以这个问题我好久都没发现

2 你一说我才想起来最新的 release 还有一个bug, 一直忘了提交

3 这边难拉的问题是同方向的父子 View 滚动, 为了既能左右翻页又能滑动删除, 我设定在想要滑动删除的时候手指停留一会儿; 由于微信改版之后, 只能获取通知栏的消息了, 所以这边就没有撤回消息的版块了. 微信记录的全是通知栏收到的消息

4 加载启动界面倒并不是因为退出了程序, 不过每次打开都会加载启动界面确实不太友好, 这个我想一下; 2333 对, 这个读权限的实时请求确实忘加了, 谢谢提醒

日志的话, 会在 /Android/data/com.qsboy.antirecall/files/logs 里每天生成 本来想着就自己看看, 确实应该有个用户可以提交的途径

最后再次感谢你的 issue !

**Comment by imbadark** [comment]
> 看到软件又更新了两个版本, 感谢fix .不过可能之前说的 2 & 3 点里有些地方说的多了, 部分意思没有表达清楚.

把关键的两个点重新说一下:
1. tim里的撤回的图片有考虑给一个本地地址保存, app内直接可以查看么? 因为聊天记录很快就会被刷过去或丢掉缓存. 
2. 微信我说的就是通知栏消息的优化:
   -  一个是目前它把所有消息全部存起来觉得不是很合理, 因为实际撤回的消息可能不到1%, 而且因为撤回标志很固定 : '*撤回了一条消息 ' or 'XX has recalled a message', 所以觉得可以加个2min的过滤选择, 可以先把两分钟内的消息都存着, 然后判断是否触发了撤回的字符串, 如果有就保留撤回前后的1/n条消息, 没有就可以清空一下.(担心存在bug的话可以作为一个可选项, 让用户选择开启)
   - 另一个是通知栏的消息锁定, 因为对你的app来说, 只要系统授予了你控制通知栏的权限, 理论上应该就能对所有通知栏的消息内容进行控制, 比如我限定它1分钟之内内容不允许变?  好像tim就有这样的效果, 但wechat不行, 如果支持的话, 可以也加个逻辑, 在通知栏每条消息推送的时候检查一下是否包含关键字 '撤回/recalled', 如果有就禁止此条消息改变? (当然如果推测错误, 没法控制通知栏内容的话, 无视就好~)

最后, 如果2.1能够实现, 软件可以一天推送一条消息:` 今天你QQ/TIM有X条撤回消息/图片, Wechat有X条..,请注意查看` 这样的提醒, 因为实测用下来很容易忘记它的存在.... 

不知道这次描述的是不是清晰一点~ 

_PS : 其实主要是因为提交issue比较正式, 很多时候遇到了小问题就懒得专门去新建一个issue, 所以之前就攒起来一次说明一下_

**Comment by cfanyyx** [comment]
@JasonQS 想问一下微信自动登陆是什么意思？

**Comment by JasonQS** [comment]
@cfanyyx 当你手机处于解锁状态时 电脑端试图登录微信 手机会自动授权

**Comment by zdbss** [comment]
软件上架酷安吧
https://www.coolapk.com

**Comment by imbadark** [comment]
许久没看了, 发现作者闭源商业化更新了, 未尝也不是一个好事.
表示支持, 如果后续想帮忙修改开发再邮件联系了~
