### ISSUE TITLE
如何获取到微信消息内容

### ISSUE THREAD

**Issue by SiberiaWolfP** [JasonQS/Anti-recall#24]
大佬，我最近在尝试实时获取微信消息内容进行一些加工的项目，本来以为AccessibilitySerive能搞这个，没想到从你的项目得知了微信放在view这一噩耗，我初次涉及这一方面，请问还有什么方法可能实现这个功能呢（xposed等除外）？

**Comment by JasonQS** [comment]
添加遮罩层。
这部分我已经实现了，但之后这个防撤回可能会要收费，所以代码没放上来。
用辅助功能检测用户界面，在适当的时候弹出自己的透明activity，这样消息就会走通知栏了。

**Comment by SiberiaWolfP** [comment]
ok，非常感谢
