### ISSUE TITLE
小米10最新版5.6.2无法使用

### ISSUE THREAD

**Issue by sjlei** [JasonQS/Anti-recall#32]
小米10，MIUI版本11.025，Android版本10。

1. `5.6.1`版本可以正常使用，但是无法获取微信应用内的消息。
2. 升级到最新`5.6.2` 之后，软件出现卡死的情况，手机温度急剧升高，重启也没用
3. 旧版本提示升级没有取消选项，只能强制升级

**Comment by JasonQS** [comment]
谢谢反馈 已修复

牧星长 <notifications@github.com> 于2020年7月6日周一 下午6:42写道：

**Comment by sjlei** [comment]
可以的，很强😲！修复速度点赞👍👍👍
