### ISSUE TITLE
闪照破解失败

### ISSUE THREAD

**Issue by sangjunke** [JasonQS/Anti-recall#41]
redmi k30 pro, android 11,
闪照破解失败 
点击看过的闪照 提示 ‘图片可能之前收到过 无法再破解’ 并不是同一文件 是不痛图片

**Comment by sjlei** [comment]
闪照破解失败+1
现在的闪照点开不能破解了，该给的权限都给了。

怎么不更新了？

**Comment by sjlei** [comment]
手机参数

![Screenshot_2021-07-13-09-54-41-792_com android se](https://user-images.githubusercontent.com/34293221/125377960-7456be80-e3c0-11eb-827c-6086442f6ae4.jpg)

**Comment by JasonQS** [comment]
Android 11 及以上 将不能破解闪照
