### ISSUE TITLE
我不得不提醒你  你用于赚钱的话可能会被告而犯罪  当然我不介意你赚钱  只是提醒

### ISSUE THREAD

**Issue by DeityZW** [JasonQS/Anti-recall#44]
我不得不提醒你  你用于赚钱的话可能会被告而犯罪  当然我不介意你赚钱  只是提醒

**Comment by soonxf** [comment]
很无语，既然开源了就不要明目张胆的收费好吧~_~

**Comment by JasonQS** [comment]
你看看 readme 我写了啥 我为啥闭源了

**Comment by qimlisky** [comment]
各位，其实在这之前qn，qa就做的很好了，但是，名声起来了，被企鹅知道了，在前几天停止维护，他们一直不接受任何形式的捐赠，哎，永别了！
