### ISSUE TITLE
5.8.6付费用户, 安卓14, QQ微信均无法显示主界面撤回消息.

### ISSUE THREAD

**Issue by laichunguang1** [JasonQS/Anti-recall#56]
如题, QQ 9.0.65, 微信8.0.48.
只是通知栏防撤回无意义, 更何况通知都不想开.
如果只支持特定版本的QQ微信, 请说明

**Comment by JasonQS** [comment]
软件里有记录下来消息吗？

CHUNGUANG LAI ***@***.***> 于 2024年7月16日周二 00:46写道：

**Comment by JasonQS** [comment]
目前支持最新版本QQ微信，旧版本不清楚

钱盛 ***@***.***> 于 2024年7月16日周二 09:25写道：
