### ISSUE TITLE
版主说的微信棘手问题是不是wx消息由textview更改成view？

### ISSUE THREAD

**Issue by xmlxin** [JasonQS/Anti-recall#9]
版主说的微信棘手问题是不是wx消息由textview更改成view？试了下老版本wx是textview可以获取到消息内容，新版本wx6.5.22变成了view。

**Comment by JasonQS** [comment]
对啊！就是这个东西

**Comment by xmlxin** [comment]
好吧，我也遇到了，非常无奈，不知道从何下手了

**Comment by klausgao** [comment]
不单单是6.5.22，我测试了，回退到6.5.13就已经变了。但是应该是还可以获取的，因为有一个叫全局拷贝的东东也是用辅助服务的，就可以。
今天才发现的问题，现在还在探索中。
有消息相互通报啊。

**Comment by zzz930404** [comment]
请问各位兄弟解决了吗？我这边遇到这个问题，那个view是不是自定义的view？然后数据的来源其实是别的地方。

**Comment by JasonQS** [comment]
我后来通过NotificationListener实现了微信的消息截取，屏幕内容还是无法获取
